version: '3.8'

services:
  web:
    build:
      context: ./web
      args:
        REACT_APP_API_URL: http://localhost:4000
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_ENABLE_CLOUD_SERVICES=${ENABLE_CLOUD_SERVICES:-false}
    depends_on:
      - api

  api:
    build: ./api
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - ANALYSIS_SERVICE_URL=http://analysis:5000
      - POSTGRES_URL=postgresql://postgres:password@postgres:5432/songsensei
      # Cloud service status flags
      - ENABLE_CLOUD_SERVICES=${ENABLE_CLOUD_SERVICES:-false}
    volumes:
      - ./api:/app
      - api_node_modules:/app/node_modules
      - temp_audio:/tmp/audio
    depends_on:
      - postgres
      - analysis

  analysis:
    build: ./analysis
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
      # Cloud service environment variables
      - HUGGINGFACE_SPLEETER_URL=${HUGGINGFACE_SPLEETER_URL}
      - HUGGINGFACE_API_TOKEN=${HUGGINGFACE_API_TOKEN}
      - GOOGLE_COLAB_URL=${GOOGLE_COLAB_URL}
      - GOOGLE_COLAB_API_KEY=${GOOGLE_COLAB_API_KEY}
      - RENDER_KEY_SERVICE_URL=${RENDER_KEY_SERVICE_URL}
      - RENDER_API_KEY=${RENDER_API_KEY}
      - GITHUB_ACTIONS_URL=${GITHUB_ACTIONS_URL}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - ENABLE_CLOUD_SERVICES=${ENABLE_CLOUD_SERVICES:-false}
    volumes:
      - ./analysis:/app
      - temp_audio:/tmp/audio
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=songsensei
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
      
  wake_spaces:
    build:
      context: .
      dockerfile: ./scripts/wake_spaces_service.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - HUGGINGFACE_SPLEETER_URL=${HUGGINGFACE_SPLEETER_URL}
      - HUGGINGFACE_DEMUCS_URL=${HUGGINGFACE_DEMUCS_URL}
      - HUGGINGFACE_API_TOKEN=${HUGGINGFACE_API_TOKEN}
      - ENABLE_CLOUD_SERVICES=${ENABLE_CLOUD_SERVICES:-false}
    restart: always

volumes:
  postgres_data:
  temp_audio:
  api_node_modules:

networks:
  default:
    name: songsensei_network
