version: '3.8'
services:
  web:
    build: ./web
    command: npm start
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://api:4000
    volumes:
      - ./web:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - api
